server:
  port: 8081

spring:
  kafka:
    bootstrap-servers: localhost:29092
    consumer:
      group-id: user-activity-consumer
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: io.confluent.kafka.serializers.KafkaAvroDeserializer
      properties:
        schema.registry.url: http://localhost:8081
        specific.avro.reader: true

